# Generated by Django 4.0.3 on 2022-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True)),
                ('author', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
