# Generated by Django 4.0.3 on 2022-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('updated_by', models.CharField(max_length=266)),
            ],
        ),
    ]
